sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose run --rm zendesk-service pytest

# after_success:
#   - bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/master/after_success.sh)
