# safelist
branches:
  only:
  # - master
  - develop

sudo: required

language: python
python:
  -  "3.7"

services:
  - docker

script: true
  # - docker-compose build
  # - docker-compose up -d
  # - docker wait zendesk-service-test
  # - docker logs -f zendesk-service-test
  # - docker-compose down
  

after_success:
  - bash docker_compose_push.sh
#   - bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/master/after_success.sh)
